# Generated by Django 5.0.4 on 2024-05-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='image_ids',
            field=models.TextField(default=''),
        ),
    ]
