# Generated by Django 5.0.4 on 2024-05-28 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_image_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+380xxxxxxxxx'. Up to 12 digits allowed.", regex='^\\+380\\d{9}$')]),
        ),
    ]
