# Generated by Django 5.0.4 on 2024-05-28 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_image_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='image_ids',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Wrong phone number format. '+380....'", regex='^\\+380\\d{9}$')]),
        ),
    ]
