# Generated by Django 5.0.4 on 2024-05-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_image_ids_alter_checkout_phone'),
        ('checkout', '0003_alter_checkout_phone'),
    ]

    operations = [
    ]
