# Generated by Django 5.0.4 on 2024-05-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_merge_20240529_1816'),
        ('checkout', '0004_remove_checkout_slug'),
    ]

    operations = [
    ]
