# Generated by Django 5.0.6 on 2024-06-02 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_merge_20240529_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Wrong phone number format. '+380....'", regex='^\\+380\\d{9}$')]),
        ),
    ]
