name: Django Web-site Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install tblib
      run: |
        pip install tblib
        pip install pytest-cov

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:photostok

    - name: Run Docker container
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'false'
        ALLOWED_HOSTS: 'localhost,127.0.0.1'
      run: docker run --name DjangoContainer -d -e DJANGO_SETTINGS_MODULE=photostok.settings -e SECRET_KEY=$SECRET_KEY -e DEBUG=$DEBUG -e ALLOWED_HOSTS=$ALLOWED_HOSTS my-image-name:photostok

    - name: Apply database migrations
      run: docker exec DjangoContainer python manage.py migrate

    - name: Collect static files
      run: docker exec DjangoContainer python manage.py collectstatic --noinput

    - name: Run pytest tests
      run: docker exec DjangoContainer pytest --cov=.

    - name: Generate HTML report
      run: docker exec DjangoContainer pytest --cov=. --cov-report=html

    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: Test and lint reports
        path: htmlcov/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: photostok
        heroku_email: ivanetspolina@knu.ua